name: 'Deploy Terraform Dependencies in Azure Gov'

on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'anoa'
        type: string
        required: true
      location:
        description: 'Azure Location'
        type: string
        required: true
        default: 'usgovvirginia'
      environment:
        description: 'Select the Environment'
        type: string
        required: true
        default: 'prod'
      createStorageAccount:
        description: 'Create Remote State Storage Account'
        required: true
        type: boolean
        default: true
        
permissions:
  id-token: write
  contents: read

env:
  org_name: ${{ github.event.inputs.organization }}
  location: ${{ github.event.inputs.location }}
  environment: ${{ github.event.inputs.environment }}
  resource_prefix: "backend"
  suffix: "rg"
  container_name: "tfstate"

jobs:
  provision-infrastructure-dependencies:
    name: "Create storage account and container for Terraform state"
    runs-on: ubuntu-latest
    steps:
      # Login to Azure Gov using Azure Credentials
      - name: Log in to Azure Gov using Azure Credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureUSGovernment'
          enable-AzPSSession: true
    
      - name: Create Resource Group
        id: rg
        run: |
          rg_name=${{ env.org_name }}-${{env.location}}-${{ env.environment }}-${{ env.resource_prefix }}-${{ env.suffix }}
          if [ $(az group exists --name $rg_name) = false ]; then
            az group create \
              --name $rg_name \
              --location ${{ env.location }} 
          fi
          echo rg_name=$rg_name >> $GITHUB_ENV
      
      - name: Create Storage Account
        if: ${{ github.event.inputs.createStorageAccount == 'true' }}
        run: |
          # Format name to 24 char limit, lowercase, and remove dashes
          st_name_prefix="$(echo st${{ env.resource_prefix }}${{ env.environment }} | cut -c1-15)"
          st_name_suffix="$(echo ${{ env.location }}${{ env.suffix }} | cut -c1-11)"
          formatted_st_name="$(echo ${st_name_prefix//-/}${st_name_suffix} | tr '[:upper:]' '[:lower:]')"
          rg_name=${{ env.org_name }}-${{env.location}}-${{ env.environment }}-${{ env.resource_prefix }}-${{ env.suffix }}
          if [ $(az storage account check-name --name $formatted_st_name --query nameAvailable) ]; then
            az storage account create \
              --name $formatted_st_name \
              --resource-group $rg_name \
              --location ${{ env.location }} \
              --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }} \
              --sku Standard_LRS

            az storage container create \
              --name ${{ env.container_name }} \
              --account-name $formatted_st_name
          fi
      - name: Upload Terraform Backend Configuration
        run: |
          echo "terraform {" > backend.tf
          echo "  backend \"azurerm\" {" >> backend.tf
          echo "    resource_group_name   = \"${{ env.org_name }}-${{env.location}}-${{ env.environment }}-${{ env.resource_prefix }}-${{ env.suffix }}\"" >> backend.tf
          echo "    storage_account_name   = \"$formatted_st_name\"" >> backend.tf
          echo "    container_name         = \"${{ env.container_name }}\"" >> backend.tf
          echo "  }" >> backend.tf
          echo "}" >> backend.tf